### PR TITLE
Support more in symengine module

### PR DESCRIPTION
**Pull request by rikardn**
* Build new symengine module with cmake
* Remove old basic module

### CODE REVIEW

**Comment by rikardn** [comment]
Diff in github looks longer than it really is. symengine.f08 was renamed to symengine.f90 to build easier with cmake.

**Comment by rikardn** [comment]
Added also:

* Rational type
* Proper unit tests
* Equality operator
* Private / public
* First function overloading (sin and cos)

**Comment by certik** [comment]
Nice. Thank you. Let me know once this is ready for review.

**Comment by rikardn** [comment]
Thanks @certik! Will do. I am starting to reach the limit of what the current cwrapper provides, but there are some more things I would like to add.

**Comment by rikardn** [comment]
This is ready for review. Check the `tests/test_basic.f90` for usage examples. The module now builds with cmake. Sorry for the huge PR.

What is missing and future potential:

* Add more symengine functions
* Use preprocessor to reduce duplication of code
* Split into multiple modules
* Improve the cwrapper: sets, refine, is_* etc

**Comment by rikardn** [comment]
Any comments @certik or can we merge?

**Pull request merged**
